name: Firmware build test

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
        
      - name: Install intelhex
        run: pip install --upgrade intelhex
        
      - name: Build NRF firmware
        run: |
          cd ARM_Tag_FW/Newton_M3_nRF52811
          pio run --environment Newton_M3_Universal
          
      - name: Build Simple_AP
        run: |
          cd ESP32_AP-Flasher
          pio run --environment Simple_AP
          pio run --target buildfs --environment Simple_AP
          
      - name: Build OpenEPaperLink_Mini_AP
        run: |
          cd ESP32_AP-Flasher
          pio run --environment OpenEPaperLink_Mini_AP
          pio run --target buildfs --environment OpenEPaperLink_Mini_AP
          
      - name: Build OpenEPaperLink_AP_and_Flasher
        run: |
          cd ESP32_AP-Flasher
          pio run --environment OpenEPaperLink_AP_and_Flasher
          pio run --target buildfs --environment OpenEPaperLink_AP_and_Flasher
          
      - name: Build ESP32_S3_16_8_YELLOW_AP]
        run: |
          cd ESP32_AP-Flasher
          pio run --environment ESP32_S3_16_8_YELLOW_AP
          pio run --target buildfs --environment ESP32_S3_16_8_YELLOW_AP
